### ISSUE TITLE
Readme file needs to be updated

### ISSUE THREAD

**Issue by Akash-SDL** [rams3sh/cowin4all#10]
When trying to run this command- uvicorn cowin4all_app:app --port 8081 --host 0.0.0.0", not able to find cowin4all_app module 
I am able to run this with webservice_hook module, though. Not sure, if that's the right way.

Please update this instruction, if you have made changes app name and its attribute.

**Comment by Akash-SDL** [comment]
Not able to find the hardcoded booking details? I see the code is referring to some JSON file.

**Comment by rams3sh** [comment]
Hey Akash 

The README requires a complete revamp. I will be updating by tonight.

Thanks for notifying!!

**Comment by Akash-SDL** [comment]
Thanks, mate! Much appreciated :)

**Comment by rams3sh** [comment]
HE @Akash-SDL , the README is updated now.

Please check. :)
