### ISSUE TITLE
Age limit and dose info missing 

### ISSUE THREAD

**Issue by parthi2929** [rams3sh/cowin4all#18]
Hi

I tried doing this and found out, in questions, the age option is not asked. We need to book for 18+, but I checked to find that question was not there. Also we should specify the does number if dose 1 or 2. 

Can you please integrate them?

**Comment by akashjarad** [comment]
i think the age option is not required as this info can be pulled out from the beneficiaries details api from background.
also for dose same would be applied from beneficiaries details .

**Comment by rams3sh** [comment]
Hey Parthi

Both of the details are being pulled from the beneficiaries info from CoWIN. You don't have to give it explicitly.

But it does display these info when it asks for confirmation from user for you to see .

Closing this issue since this is being done already automatically .
