### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by hpk22** [rams3sh/cowin4all#2]
Hey your project looked promising. But could it be possible to make it easy for less tech oriented people like me 😅. Like an extension or website or telegram bot

**Comment by rams3sh** [comment]
Hey hpk22

Thanks for your interest. Really appreciate it !!

I was working on optimizing the code for last few days. I will be working on to release a basic script for easy installation and usage of this app.

Please do check this space for updates in next two days !!

:) 

Cheers and stay safe !!

**Comment by rams3sh** [comment]
Hey @hpk22 

I have revamped the documentation completely.

Hope the new version provides you enough guidance for setting this up.

Feel free to re-open this ticket if you still find it challenging.
