### ISSUE TITLE
Unable to install termux-api using apt install termux-api

### ISSUE THREAD

**Issue by kennethkth** [rams3sh/cowin4all#22]
Device: Redmi Note 9 pro
https://i.imgur.com/mxVs2CP.jpg

**Comment by kennethkth** [comment]
Fixed this by first running `apt update` and then `apt install termux-api`. Kindly Update the README
https://github.com/termux/termux-api-package/issues/131

**Comment by kennethkth** [comment]
I have tested the app using `cowin4all -e`. And it is working fine on my device now. Just wanted to know where the pdf will be stored in an android device

**Comment by rams3sh** [comment]
Type `ls` in the termux command line and you would be able to see the pdf. Type `pwd` to find the path.

Open this path in some UI based file manager and you would be able to read the pdf.

Since this has been already resolved, closing this.
